/**
 * AudioDescriptionService – AI-powered audio description for blind and
 * low-vision users.
 *
 * Responsibilities:
 *  1. Analyze video frames to detect visual events using an AI vision model.
 *  2. Detect natural pauses in dialogue where descriptions can be inserted.
 *  3. Generate human-readable descriptions covering:
 *       - Scene changes and environment context
 *       - On-screen text (titles, banners, captions)
 *       - Important actions and character movements
 *       - Character expressions and emotional context
 *  4. Convert descriptions to speech via TTS and produce a separate audio track.
 *  5. Provide a structured timeline of audio description cues for the player.
 *
 * Production: configure VISION_API_KEY (OpenAI GPT-4V or similar),
 * TTS_API_KEY (ElevenLabs), and FFMPEG availability.  The stub
 * implementation mirrors the full API contract and is safe to use in tests.
 */

import * as fs from "fs";
import * as path from "path";
import logger from "../logger";

// ---------------------------------------------------------------------------
// Constants
// ---------------------------------------------------------------------------

const VISION_API_URL =
  process.env.VISION_API_URL ?? "https://api.openai.com/v1/chat/completions";
const VISION_API_KEY = process.env.VISION_API_KEY ?? "";
const VISION_MODEL = process.env.VISION_MODEL ?? "gpt-4o";

const AD_TTS_API_URL =
  process.env.TTS_API_URL ?? "https://api.elevenlabs.io/v1/text-to-speech";
const AD_TTS_API_KEY = process.env.TTS_API_KEY ?? "";
/** Narrator voice ID for audio descriptions (ElevenLabs or custom) */
const AD_NARRATOR_VOICE_ID =
  process.env.AD_NARRATOR_VOICE_ID ?? "pNInz6obpgDQGcFmaJgB"; // "Adam" on ElevenLabs

const AD_OUTPUT_ROOT =
  process.env.AD_OUTPUT_ROOT ?? "/tmp/quanttube-audio-desc";

/** Minimum dialogue pause (in seconds) required to insert a description */
const MIN_PAUSE_DURATION_SECS = 1.5;

/** Maximum description audio duration as a fraction of available pause */
const MAX_PAUSE_USAGE_RATIO = 0.85;

/** Frame extraction rate for scene analysis (frames per second) */
const ANALYSIS_FRAME_RATE = 1; // 1 fps is sufficient for description purposes

/** Maximum number of frames to analyze per video (cost guard) */
const MAX_FRAMES_TO_ANALYZE = 120;

// ---------------------------------------------------------------------------
// Type definitions
// ---------------------------------------------------------------------------

export type VisualEventType =
  | "scene_change"
  | "on_screen_text"
  | "character_action"
  | "character_expression"
  | "environment_change"
  | "graphic_element"
  | "object_introduced"
  | "person_identified";

export interface VisualEvent {
  /** Event category */
  type: VisualEventType;
  /** Timestamp in the video (seconds) */
  timestamp: number;
  /** Confidence 0–1 */
  confidence: number;
  /** Raw description generated by the vision model */
  rawDescription: string;
  /** Frame index that triggered this event */
  frameIndex: number;
}

export interface DialoguePause {
  /** Start of the pause in seconds */
  start: number;
  /** End of the pause in seconds */
  end: number;
  /** Duration of the pause in seconds */
  duration: number;
  /** Whether this pause has been assigned a description */
  assigned: boolean;
}

export interface AudioDescriptionCue {
  /** Unique sequential index */
  index: number;
  /** When to start playing this description (seconds) */
  insertAt: number;
  /** Duration of the description audio in seconds */
  durationSecs: number;
  /** The text of the description */
  text: string;
  /** The visual event(s) that prompted this description */
  visualEvents: VisualEvent[];
  /** Path to the TTS audio file (null in stub mode) */
  audioPath: string | null;
  /** Whether the audio was generated (false in stub/missing-key mode) */
  audioGenerated: boolean;
}

export interface FrameAnalysisResult {
  videoId: string;
  frameCount: number;
  analyzedFrameCount: number;
  visualEvents: VisualEvent[];
  analyzedAt: string;
}

export type AudioDescriptionJobStatus =
  | "queued"
  | "extracting_frames"
  | "analyzing_frames"
  | "detecting_pauses"
  | "generating_descriptions"
  | "synthesizing_audio"
  | "completed"
  | "failed";

export interface AudioDescriptionJob {
  jobId: string;
  videoId: string;
  videoPath: string;
  /** Audio track path extracted from the video (for pause detection) */
  audioPath: string;
  status: AudioDescriptionJobStatus;
  frameAnalysis: FrameAnalysisResult | null;
  dialoguePauses: DialoguePause[];
  cues: AudioDescriptionCue[];
  /** Combined audio description track path */
  combinedAudioPath: string | null;
  errorMessage: string | null;
  createdAt: string;
  updatedAt: string;
  completedAt: string | null;
}

export interface GenerateAudioDescriptionParams {
  videoId: string;
  /** Path to the source video file */
  videoPath: string;
  /** Path to the extracted audio track (for dialogue pause detection) */
  audioPath: string;
  /** Dialogue transcript segments to identify pauses (optional but improves accuracy) */
  dialogueSegments?: Array<{ start: number; end: number; text: string }>;
}

// ---------------------------------------------------------------------------
// In-memory job store
// ---------------------------------------------------------------------------

const audioDescriptionJobs = new Map<string, AudioDescriptionJob>();

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

function nowIso(): string {
  return new Date().toISOString();
}

function randomId(): string {
  return `adsc-${Math.random().toString(36).substring(2, 14)}`;
}

function ensureDir(dir: string): void {
  if (!fs.existsSync(dir)) {
    fs.mkdirSync(dir, { recursive: true });
  }
}

/**
 * Sanitize a path component to prevent directory traversal.
 * Keeps alphanumerics, hyphens and underscores only.
 */
function sanitizePathComponent(component: string): string {
  return component.replace(/[^a-zA-Z0-9\-_]/g, "_");
}

/**
 * Build a safe output path within a given root, validating no traversal occurs.
 */
function safeOutputPath(root: string, ...segments: string[]): string {
  const sanitized = segments.map(sanitizePathComponent);
  const resolved = path.resolve(root, ...sanitized);
  const resolvedRoot = path.resolve(root);
  if (!resolved.startsWith(resolvedRoot + path.sep) && resolved !== resolvedRoot) {
    throw new Error(`Path traversal detected: ${resolved} is outside ${resolvedRoot}`);
  }
  return resolved;
}

function sleep(ms: number): Promise<void> {
  return new Promise((resolve) => setTimeout(resolve, ms));
}

// ---------------------------------------------------------------------------
// Frame extraction (stub)
// ---------------------------------------------------------------------------

export interface ExtractedFrame {
  frameIndex: number;
  timestamp: number;
  /** Base64-encoded JPEG image data (empty string in stub mode) */
  base64Image: string;
  /** Width in pixels */
  width: number;
  /** Height in pixels */
  height: number;
}

/**
 * Extract frames from a video file at a given frame rate.
 *
 * In production: uses ffmpeg to extract JPEG frames at ANALYSIS_FRAME_RATE fps.
 * Stub: generates metadata-only frame descriptors with empty image data.
 *
 * The estimated duration is derived from the audioPath size as a very rough
 * proxy when the actual video duration is unavailable.
 */
export async function extractVideoFrames(
  videoPath: string,
  outputDir: string,
  estimatedDurationSecs: number
): Promise<ExtractedFrame[]> {
  ensureDir(outputDir);

  const totalFrames = Math.min(
    Math.ceil(estimatedDurationSecs * ANALYSIS_FRAME_RATE),
    MAX_FRAMES_TO_ANALYZE
  );

  if (!fs.existsSync(videoPath) || !VISION_API_KEY) {
    logger.warn(
      { videoPath },
      "Video file absent or VISION_API_KEY not configured – using stub frames"
    );
    return Array.from({ length: totalFrames }, (_, i) => ({
      frameIndex: i,
      timestamp: i / ANALYSIS_FRAME_RATE,
      base64Image: "",
      width: 1920,
      height: 1080,
    }));
  }

  // Production: invoke ffmpeg to extract frames
  const framePattern = path.join(outputDir, "frame_%05d.jpg");
  const ffmpegCmd = [
    "ffmpeg",
    "-i", videoPath,
    "-vf", `fps=${ANALYSIS_FRAME_RATE}`,
    "-vframes", String(totalFrames),
    "-q:v", "3",
    "-y",
    framePattern,
  ];

  logger.info({ videoPath, totalFrames, framePattern }, "Extracting video frames");

  const { execFile } = await import("child_process");
  const { promisify } = await import("util");
  const execFileAsync = promisify(execFile);

  await execFileAsync(ffmpegCmd[0]!, ffmpegCmd.slice(1));

  const frames: ExtractedFrame[] = [];
  for (let i = 0; i < totalFrames; i++) {
    const framePath = path.join(outputDir, `frame_${String(i + 1).padStart(5, "0")}.jpg`);
    if (fs.existsSync(framePath)) {
      const imageData = fs.readFileSync(framePath);
      frames.push({
        frameIndex: i,
        timestamp: i / ANALYSIS_FRAME_RATE,
        base64Image: imageData.toString("base64"),
        width: 1920,
        height: 1080,
      });
    }
  }

  return frames;
}

// ---------------------------------------------------------------------------
// Scene change detection
// ---------------------------------------------------------------------------

/**
 * Compare two base64 frames and return a scene-change confidence score.
 *
 * Production: uses perceptual hashing (pHash) or a CNN-based change detector.
 * Stub: returns a deterministic pseudo-score based on frame index delta.
 */
export function detectSceneChange(
  frameA: ExtractedFrame,
  frameB: ExtractedFrame
): number {
  if (!frameA.base64Image || !frameB.base64Image) {
    // Stub: generate pseudo-random scene change probability
    const timeDelta = Math.abs(frameB.timestamp - frameA.timestamp);
    // Scene changes are more likely after longer intervals
    const baseProb = Math.min(0.15 * timeDelta, 0.5);
    // Use frame indices as a pseudo-random seed
    const seed = (frameA.frameIndex * 7919 + frameB.frameIndex * 6271) % 1000;
    return baseProb + (seed / 1000) * 0.3;
  }

  // Rough pixel similarity estimate via sample comparison
  const aLen = frameA.base64Image.length;
  const bLen = frameB.base64Image.length;
  const sizeDiff = Math.abs(aLen - bLen) / Math.max(aLen, bLen);
  return Math.min(sizeDiff * 3, 1.0);
}

// ---------------------------------------------------------------------------
// Vision model integration
// ---------------------------------------------------------------------------

const DESCRIPTION_PROMPT = `You are an expert audio description writer for visually impaired viewers.
Analyze the video frame and describe:
1. Any scene changes or new environments
2. On-screen text, titles, or captions
3. Important character actions and movements
4. Character expressions and emotional state
5. Significant objects or graphics entering the frame

Keep descriptions concise (under 20 words), factual, and in present tense.
Focus on visually significant information that is not conveyed by dialogue.
Output ONLY the description text, nothing else.`;

interface VisionAPIMessage {
  role: "user" | "assistant" | "system";
  content: string | Array<{ type: string; text?: string; image_url?: { url: string; detail: string } }>;
}

interface VisionAPIResponse {
  choices?: Array<{
    message?: { content?: string };
  }>;
}

/**
 * Analyze a single video frame using a vision AI model.
 *
 * Returns the generated description text.
 * Falls back to a deterministic stub description when the API key is absent.
 */
async function analyzeFrame(
  frame: ExtractedFrame,
  context: string
): Promise<string> {
  if (!VISION_API_KEY || !frame.base64Image) {
    // Stub descriptions keyed by frame index for reproducibility
    const stubDescriptions = [
      "A presenter stands at a podium in a conference room.",
      "Text on screen reads: 'Chapter 1: Introduction'.",
      "The scene transitions to an outdoor city street.",
      "A character smiles and gestures towards a whiteboard.",
      "Close-up of hands typing on a laptop keyboard.",
      "Two people sit across from each other at a table.",
      "An animated chart appears showing upward growth.",
      "The camera pans across a mountain landscape.",
      "A notification popup appears in the corner of the screen.",
      "The speaker looks directly at the camera.",
    ];
    const idx = frame.frameIndex % stubDescriptions.length;
    return stubDescriptions[idx]!;
  }

  const messages: VisionAPIMessage[] = [
    {
      role: "system",
      content: DESCRIPTION_PROMPT,
    },
    {
      role: "user",
      content: [
        {
          type: "text",
          text: context
            ? `Previous context: ${context}\n\nDescribe what you see in this frame:`
            : "Describe what you see in this frame:",
        },
        {
          type: "image_url",
          image_url: {
            url: `data:image/jpeg;base64,${frame.base64Image}`,
            detail: "low",
          },
        },
      ],
    },
  ];

  const response = await fetch(VISION_API_URL, {
    method: "POST",
    headers: {
      Authorization: `Bearer ${VISION_API_KEY}`,
      "Content-Type": "application/json",
    },
    body: JSON.stringify({
      model: VISION_MODEL,
      messages,
      max_tokens: 100,
      temperature: 0.3,
    }),
  });

  if (!response.ok) {
    const errText = await response.text();
    throw new Error(`Vision API ${response.status}: ${errText}`);
  }

  const data = (await response.json()) as VisionAPIResponse;
  return (data.choices?.[0]?.message?.content ?? "").trim();
}

/**
 * Classify the type of visual event from its description text.
 */
export function classifyVisualEvent(description: string): VisualEventType {
  const lower = description.toLowerCase();

  if (lower.includes("text") || lower.includes("reads:") || lower.includes("caption") ||
      lower.includes("title") || lower.includes("screen") || lower.includes("subtitle")) {
    return "on_screen_text";
  }
  if (lower.includes("smile") || lower.includes("laugh") || lower.includes("frown") ||
      lower.includes("expression") || lower.includes("emotion") || lower.includes("face")) {
    return "character_expression";
  }
  if (lower.includes("scene") || lower.includes("transition") || lower.includes("cut") ||
      lower.includes("exterior") || lower.includes("interior")) {
    return "scene_change";
  }
  if (lower.includes("gesture") || lower.includes("walk") || lower.includes("run") ||
      lower.includes("sits") || lower.includes("stands") || lower.includes("action") ||
      lower.includes("movement") || lower.includes("typing") || lower.includes("holds")) {
    return "character_action";
  }
  if (lower.includes("chart") || lower.includes("graphic") || lower.includes("animation") ||
      lower.includes("icon") || lower.includes("logo") || lower.includes("popup")) {
    return "graphic_element";
  }
  if (lower.includes("room") || lower.includes("outdoor") || lower.includes("street") ||
      lower.includes("office") || lower.includes("landscape") || lower.includes("background")) {
    return "environment_change";
  }
  if (lower.includes("person") || lower.includes("man") || lower.includes("woman") ||
      lower.includes("child") || lower.includes("speaker") || lower.includes("presenter")) {
    return "person_identified";
  }

  return "object_introduced";
}

// ---------------------------------------------------------------------------
// Frame analysis pipeline
// ---------------------------------------------------------------------------

/**
 * Analyze all extracted frames and produce a list of VisualEvents.
 *
 * Deduplicates consecutive similar descriptions and only emits events
 * when the visual content changes meaningfully.
 */
export async function analyzeFrames(
  videoId: string,
  frames: ExtractedFrame[]
): Promise<FrameAnalysisResult> {
  const visualEvents: VisualEvent[] = [];
  let previousDescription = "";
  let analyzedCount = 0;

  for (let i = 0; i < frames.length; i++) {
    const frame = frames[i]!;

    // Check for scene change
    let sceneChangeConfidence = 0;
    if (i > 0) {
      sceneChangeConfidence = detectSceneChange(frames[i - 1]!, frame);
    }

    // Analyze every 5th frame (plus scene changes) to limit API costs
    const shouldAnalyze = i === 0 || i % 5 === 0 || sceneChangeConfidence > 0.4;
    if (!shouldAnalyze) continue;

    const description = await analyzeFrame(frame, previousDescription);
    analyzedCount++;

    // Skip if description is nearly identical to previous (no meaningful change)
    if (description && description !== previousDescription) {
      const eventType = sceneChangeConfidence > 0.4
        ? "scene_change"
        : classifyVisualEvent(description);

      visualEvents.push({
        type: eventType,
        timestamp: frame.timestamp,
        confidence: Math.max(0.7, 1.0 - sceneChangeConfidence * 0.5),
        rawDescription: description,
        frameIndex: frame.frameIndex,
      });

      previousDescription = description;
    }

    // Small delay between API calls to respect rate limits
    if (i < frames.length - 1 && VISION_API_KEY) {
      await sleep(100);
    }
  }

  return {
    videoId,
    frameCount: frames.length,
    analyzedFrameCount: analyzedCount,
    visualEvents,
    analyzedAt: nowIso(),
  };
}

// ---------------------------------------------------------------------------
// Dialogue pause detection
// ---------------------------------------------------------------------------

/**
 * Detect natural pauses in dialogue where audio descriptions can be inserted.
 *
 * When dialogue segments are provided, pauses are the gaps between them.
 * Otherwise, a set of evenly-spaced synthetic pauses is returned.
 */
export function detectDialoguePauses(
  dialogueSegments: Array<{ start: number; end: number; text: string }>,
  videoDurationSecs: number
): DialoguePause[] {
  const pauses: DialoguePause[] = [];

  if (dialogueSegments.length === 0) {
    // No dialogue data: create a pause every 30 seconds
    const interval = 30;
    for (let t = 5; t < videoDurationSecs - 5; t += interval) {
      pauses.push({
        start: t,
        end: t + MIN_PAUSE_DURATION_SECS * 2,
        duration: MIN_PAUSE_DURATION_SECS * 2,
        assigned: false,
      });
    }
    return pauses;
  }

  // Sort segments by start time
  const sorted = [...dialogueSegments].sort((a, b) => a.start - b.start);

  // Gap before first segment
  if (sorted[0]!.start > MIN_PAUSE_DURATION_SECS) {
    pauses.push({
      start: 0,
      end: sorted[0]!.start,
      duration: sorted[0]!.start,
      assigned: false,
    });
  }

  // Gaps between consecutive segments
  for (let i = 0; i < sorted.length - 1; i++) {
    const gapStart = sorted[i]!.end;
    const gapEnd = sorted[i + 1]!.start;
    const gapDuration = gapEnd - gapStart;

    if (gapDuration >= MIN_PAUSE_DURATION_SECS) {
      pauses.push({
        start: gapStart,
        end: gapEnd,
        duration: gapDuration,
        assigned: false,
      });
    }
  }

  // Gap after last segment
  const lastEnd = sorted[sorted.length - 1]!.end;
  if (videoDurationSecs - lastEnd > MIN_PAUSE_DURATION_SECS) {
    pauses.push({
      start: lastEnd,
      end: videoDurationSecs,
      duration: videoDurationSecs - lastEnd,
      assigned: false,
    });
  }

  return pauses;
}

// ---------------------------------------------------------------------------
// Description generation
// ---------------------------------------------------------------------------

/**
 * Merge visual events that are temporally close and thematically related
 * into a single combined description suitable for audio output.
 */
export function composeDescriptionText(events: VisualEvent[]): string {
  if (events.length === 0) return "";
  if (events.length === 1) return events[0]!.rawDescription;

  // For multiple events, combine into a flowing sentence
  const parts = events.map((e) => e.rawDescription.replace(/\.$/, ""));
  if (parts.length === 2) {
    return `${parts[0]}, then ${parts[1]}.`;
  }
  const last = parts.pop()!;
  return `${parts.join("; ")}, and ${last}.`;
}

/**
 * Assign visual events to the best available dialogue pauses.
 *
 * Each visual event is placed in the nearest subsequent pause that has
 * sufficient available duration.
 */
export function assignEventsToPauses(
  events: VisualEvent[],
  pauses: DialoguePause[],
  estimatedWordsPerSecond = 2.5
): AudioDescriptionCue[] {
  const cues: AudioDescriptionCue[] = [];
  const pauseUsage = new Map<number, number>(); // pause index → seconds used

  for (const event of events) {
    // Find the best pause: next available pause after (or at) the event timestamp
    let bestPauseIdx = -1;
    let bestDelay = Infinity;

    for (let i = 0; i < pauses.length; i++) {
      const pause = pauses[i]!;
      if (pause.start < event.timestamp) continue; // pause is before the event

      const used = pauseUsage.get(i) ?? 0;
      const available = pause.duration * MAX_PAUSE_USAGE_RATIO - used;
      if (available <= 0) continue; // pause is fully used

      const delay = pause.start - event.timestamp;
      if (delay < bestDelay) {
        bestDelay = delay;
        bestPauseIdx = i;
      }
    }

    if (bestPauseIdx === -1) continue; // No suitable pause found

    const pause = pauses[bestPauseIdx]!;
    const text = event.rawDescription;
    const wordCount = text.split(/\s+/).filter(Boolean).length;
    const estimatedDuration = Math.ceil((wordCount / estimatedWordsPerSecond) * 10) / 10;

    const used = pauseUsage.get(bestPauseIdx) ?? 0;
    const available = pause.duration * MAX_PAUSE_USAGE_RATIO - used;
    if (estimatedDuration > available) continue;

    const insertAt = pause.start + used + 0.2; // 200ms buffer
    pauseUsage.set(bestPauseIdx, used + estimatedDuration + 0.3);

    cues.push({
      index: cues.length,
      insertAt,
      durationSecs: estimatedDuration,
      text,
      visualEvents: [event],
      audioPath: null,
      audioGenerated: false,
    });
  }

  return cues.sort((a, b) => a.insertAt - b.insertAt);
}

// ---------------------------------------------------------------------------
// TTS synthesis for audio descriptions
// ---------------------------------------------------------------------------

/**
 * Synthesize a single audio description cue via TTS.
 *
 * Production: POSTs to ElevenLabs with a dedicated narrator voice.
 * Stub: writes a placeholder file when TTS_API_KEY is absent.
 */
async function synthesizeDescriptionCue(
  cue: AudioDescriptionCue,
  outputPath: string
): Promise<{ audioPath: string; durationSecs: number }> {
  ensureDir(path.dirname(outputPath));

  if (!AD_TTS_API_KEY) {
    const stubContent = `STUB_AD_AUDIO:cue=${cue.index}:text=${cue.text.substring(0, 30)}`;
    fs.writeFileSync(outputPath, stubContent);
    return { audioPath: outputPath, durationSecs: cue.durationSecs };
  }

  const payload = {
    text: cue.text,
    model_id: "eleven_multilingual_v2",
    voice_settings: {
      stability: 0.7,
      similarity_boost: 0.7,
      style: 0.1,
      use_speaker_boost: false,
      speaking_rate: 1.1, // Slightly faster for time-constrained insertions
    },
  };

  const response = await fetch(`${AD_TTS_API_URL}/${AD_NARRATOR_VOICE_ID}`, {
    method: "POST",
    headers: {
      "xi-api-key": AD_TTS_API_KEY,
      "Content-Type": "application/json",
      Accept: "audio/mpeg",
    },
    body: JSON.stringify(payload),
  });

  if (!response.ok) {
    throw new Error(`TTS API ${response.status}: ${await response.text()}`);
  }

  const audioBuffer = Buffer.from(await response.arrayBuffer());
  fs.writeFileSync(outputPath, audioBuffer);

  // Approximate duration from mp3 bitrate (128 kbps)
  const durationSecs = (audioBuffer.length * 8) / (128 * 1000);

  return { audioPath: outputPath, durationSecs };
}

/**
 * Build an ffmpeg command to mix audio description track with the original
 * video's audio at a specified insertion timestamp.
 *
 * The description audio is ducked in at full volume; original audio is
 * attenuated to 15% during the description for clarity.
 */
export function buildAudioDescriptionMixCommand(
  originalAudioPath: string,
  descriptionAudioPath: string,
  insertAtSecs: number,
  outputPath: string
): string {
  const delay = Math.round(insertAtSecs * 1000); // ms for adelay filter
  return (
    `ffmpeg -i "${originalAudioPath}" -i "${descriptionAudioPath}" ` +
    `-filter_complex ` +
    `"[1:a]adelay=${delay}|${delay}[delayed_desc];` +
    `[0:a][delayed_desc]sidechaincompress=threshold=0.05:ratio=5:attack=200:release=1000[out]" ` +
    `-map "[out]" -c:a aac -b:a 192k -y "${outputPath}"`
  );
}

// ---------------------------------------------------------------------------
// Public API
// ---------------------------------------------------------------------------

/**
 * Submit an audio description generation job.
 */
export function generateAudioDescription(
  params: GenerateAudioDescriptionParams
): AudioDescriptionJob {
  const {
    videoId,
    videoPath,
    audioPath,
    dialogueSegments = [],
  } = params;

  const jobId = randomId();
  const now = nowIso();

  const job: AudioDescriptionJob = {
    jobId,
    videoId,
    videoPath,
    audioPath,
    status: "queued",
    frameAnalysis: null,
    dialoguePauses: [],
    cues: [],
    combinedAudioPath: null,
    errorMessage: null,
    createdAt: now,
    updatedAt: now,
    completedAt: null,
  };

  audioDescriptionJobs.set(jobId, job);

  runAudioDescriptionJob(jobId, dialogueSegments).catch((err) => {
    logger.error({ jobId, err }, "Audio description job error");
  });

  logger.info(
    { jobId, videoId, videoPath, audioPath },
    "Audio description generation job queued"
  );

  return job;
}

/**
 * Retrieve an audio description job by ID.
 */
export function getAudioDescriptionJob(jobId: string): AudioDescriptionJob | undefined {
  return audioDescriptionJobs.get(jobId);
}

/**
 * List audio description jobs, optionally filtered by videoId.
 */
export function listAudioDescriptionJobs(videoId?: string): AudioDescriptionJob[] {
  const all = Array.from(audioDescriptionJobs.values());
  if (videoId) return all.filter((j) => j.videoId === videoId);
  return all;
}

/**
 * Retrieve the cue timeline for a completed job (used by the player).
 */
export function getAudioDescriptionCues(jobId: string): AudioDescriptionCue[] {
  return audioDescriptionJobs.get(jobId)?.cues ?? [];
}

// ---------------------------------------------------------------------------
// Async job runner
// ---------------------------------------------------------------------------

async function runAudioDescriptionJob(
  jobId: string,
  dialogueSegments: Array<{ start: number; end: number; text: string }>
): Promise<void> {
  const job = audioDescriptionJobs.get(jobId);
  if (!job) return;

  try {
    const outputDir = safeOutputPath(AD_OUTPUT_ROOT, job.videoId, job.jobId);
    ensureDir(outputDir);

    // Estimate video duration from audio file size (very rough; 128 kbps mp3)
    let estimatedDurationSecs = 120; // default fallback
    if (fs.existsSync(job.audioPath)) {
      const stat = fs.statSync(job.audioPath);
      estimatedDurationSecs = Math.max(10, (stat.size * 8) / (128 * 1000));
    } else if (dialogueSegments.length > 0) {
      const maxEnd = Math.max(...dialogueSegments.map((s) => s.end));
      estimatedDurationSecs = maxEnd + 10;
    }

    // Step 1: Extract video frames
    job.status = "extracting_frames";
    job.updatedAt = nowIso();

    const framesDir = path.join(outputDir, "frames");
    const frames = await extractVideoFrames(
      job.videoPath,
      framesDir,
      estimatedDurationSecs
    );

    // Step 2: Analyze frames
    job.status = "analyzing_frames";
    job.updatedAt = nowIso();

    const frameAnalysis = await analyzeFrames(job.videoId, frames);
    job.frameAnalysis = frameAnalysis;

    // Step 3: Detect dialogue pauses
    job.status = "detecting_pauses";
    job.updatedAt = nowIso();

    const pauses = detectDialoguePauses(dialogueSegments, estimatedDurationSecs);
    job.dialoguePauses = pauses;

    // Step 4: Generate description cues
    job.status = "generating_descriptions";
    job.updatedAt = nowIso();

    const cues = assignEventsToPauses(frameAnalysis.visualEvents, pauses);
    job.cues = cues;

    // Step 5: Synthesize audio for each cue
    job.status = "synthesizing_audio";
    job.updatedAt = nowIso();

    for (let i = 0; i < cues.length; i++) {
      const cue = cues[i]!;
      const cueAudioPath = path.join(outputDir, `cue_${String(i).padStart(4, "0")}.mp3`);

      try {
        const { audioPath: synthesizedPath, durationSecs } = await synthesizeDescriptionCue(
          cue,
          cueAudioPath
        );
        cue.audioPath = synthesizedPath;
        cue.durationSecs = durationSecs;
        cue.audioGenerated = !!AD_TTS_API_KEY;
      } catch (cueErr) {
        const cueErrMsg = cueErr instanceof Error ? cueErr.message : String(cueErr);
        logger.warn({ jobId, cueIndex: i, err: cueErrMsg }, "Failed to synthesize description cue");
      }
    }

    // Build combined audio track path (actual mixing requires ffmpeg in production)
    const combinedPath = path.join(outputDir, "audio_descriptions_combined.mp3");
    if (!AD_TTS_API_KEY) {
      fs.writeFileSync(
        combinedPath,
        `STUB_COMBINED_AD:${sanitizePathComponent(job.videoId)}:cues=${cues.length}`
      );
    }
    job.combinedAudioPath = combinedPath;

    job.status = "completed";
    job.completedAt = nowIso();
    job.updatedAt = nowIso();

    logger.info(
      {
        jobId,
        videoId: job.videoId,
        visualEvents: frameAnalysis.visualEvents.length,
        pauses: pauses.length,
        cues: cues.length,
      },
      "Audio description generation completed"
    );
  } catch (err) {
    const msg = err instanceof Error ? err.message : String(err);
    job.status = "failed";
    job.errorMessage = msg;
    job.updatedAt = nowIso();
    logger.error({ jobId, err: msg }, "Audio description generation failed");
  }
}

// ---------------------------------------------------------------------------
// Test helper
// ---------------------------------------------------------------------------

export function _resetAudioDescriptionJobs(): void {
  audioDescriptionJobs.clear();
}
